datadir: 'data'

preprocess:
  target_size: [256, 256]

model:
  image_size: ${preprocess.target_size}
  effnet_weights: 'assets/effnet_official/efficientnetb0_notop.h5'
  use_weights: 'assets/universal-sentence-encoder-multilingual_3'

train:
  n_splits: 5
  epochs: 10
  batch_size: 16
  learning_rate: 0.001
  patience: 5

logdir: 'outputs/exp001'
