datadir: 'data'

preprocess:
  target_size: [256, 256]
  tfidf:
    stop_words: 'english'
    binary: True
    max_features: 25000
  encoder_weights: 'assets/universal-sentence-encoders/universal-sentence-encoder-multilingual_3'

model:
  image_size: ${preprocess.target_size}
  tfidf_dim: ${preprocess.tfidf.max_features}
  final_feature_dim: 1024
  effnet_weights: 'assets/effnet_official/noisy_student_efficientnet-b0_notop.h5'
  circle_loss_params:
    margin: 0.25
    scale: 256

train:
  n_splits: 5
  epochs: 50
  batch_size: 16
  learning_rate: 0.001
  score_callback:
    neighbor_thr: 0.4
    patience: 5

logdir: 'outputs'
