datadir: 'data'

preprocess:
  target_size: [320, 320]
  tfidf:
    stop_words: 'english'
    binary: True
    max_features: 25000
  encoder_weights: 'assets/universal-sentence-encoders/universal-sentence-encoder-multilingual_3'

model:
  image_size: ${preprocess.target_size}
  tfidf_dim: ${preprocess.tfidf.max_features}
  final_feature_dim: 1024
  effnet_type: 'EfficientNetB2'
  effnet_weights: 'assets/effnet_official/noisy_student_efficientnet-b2_notop.h5'
  circle_loss:
    margin: 0.25
    scale: 256

train:
  n_splits: 5
  epochs: 30
  batch_size: 16
  learning_rate: 0.001
  callback:
    patience: 3

logdir: 'outputs'
