datadir: 'data'

preprocess:
  target_size: [256, 256]
  use_weights: 'assets/universal-sentence-encoder-multilingual_3'

model:
  image_size: ${preprocess.target_size}
  effnet_weights: 'assets/effnet_official/noisy_student_efficientnet-b0_notop.h5'

train:
  n_splits: 5
  epochs: 10
  batch_size: 16
  learning_rate: 0.001
  patience: 5

logdir: 'outputs'
